//
// BulkCardOrdersAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class BulkCardOrdersAPI {
    /**
     List bulk card orders

     - parameter count: (query) Number of bulk card orders to retrieve. (optional, default to 5)
     - parameter startIndex: (query) Sort order index of the first resource in the returned array. (optional, default to 0)
     - parameter sortBy: (query) Field on which to sort. Use any field in the resource model, or one of the system fields &#x60;lastModifiedTime&#x60; or &#x60;createdTime&#x60;. Prefix the field name with a hyphen (&#x60;-&#x60;) to sort in descending order. Omit the hyphen to sort in ascending order. (optional, default to -createdTime)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getBulkissuances(count: Int? = nil, startIndex: Int? = nil, sortBy: String? = nil, completion: @escaping ((_ data: BulkCardOrderListResponse?,_ error: Error?) -> Void)) {
        getBulkissuancesWithRequestBuilder(count: count, startIndex: startIndex, sortBy: sortBy).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     List bulk card orders
     - GET /bulkissuances

     - BASIC:
       - type: http
       - name: mqAppAndAccessToken
     - examples: [{contentType=application/json, example={
  "is_more" : false,
  "data" : [ {
    "created_time" : "2000-01-23T04:56:07.000+00:00",
    "expedite" : false,
    "user_association" : {
      "single_inventory_user_token" : "false",
      "single_inventory_user" : false
    },
    "name_line1_start_index" : 2,
    "card_allocation" : 30137,
    "name_line1_end_index" : 5,
    "provider_shipping_method" : "provider_shipping_method",
    "provider_tracking_number" : "provider_tracking_number",
    "cards_processed" : 1,
    "token" : "token",
    "card_product_token" : "card_product_token",
    "card_fulfillment_time" : "2000-01-23T04:56:07.000+00:00",
    "name_line_1_numeric_postfix" : false,
    "name_line_1_random_postfix" : false,
    "expiration_offset" : {
      "unit" : "YEARS",
      "value" : 5
    },
    "fulfillment" : {
      "shipping" : {
        "care_of_line" : "care_of_line",
        "method" : "LOCAL_MAIL",
        "recipient_address" : {
          "zip" : "zip",
          "country" : "country",
          "address2" : "address2",
          "city" : "city",
          "phone" : "phone",
          "address1" : "address1",
          "last_name" : "last_name",
          "state" : "state",
          "middle_name" : "middle_name",
          "postal_code" : "postal_code",
          "first_name" : "first_name"
        }
      },
      "card_personalization" : {
        "carrier" : {
          "message_file" : "message_file",
          "logo_file" : "logo_file",
          "message_line" : "message_line",
          "template_id" : "template_id",
          "logo_thumbnail_file" : "logo_thumbnail_file"
        },
        "images" : {
          "carrier" : {
            "message_1" : "message_1",
            "name" : "name"
          },
          "signature" : {
            "name" : "name"
          },
          "carrier_return_window" : {
            "name" : "name"
          },
          "card" : {
            "name" : "name",
            "thermal_color" : "thermal_color"
          }
        },
        "text" : {
          "name_line_1" : {
            "value" : "value"
          }
        },
        "perso_type" : "EMBOSS"
      }
    },
    "provider_ship_date" : "2000-01-23T04:56:07.000+00:00"
  }, {
    "created_time" : "2000-01-23T04:56:07.000+00:00",
    "expedite" : false,
    "user_association" : {
      "single_inventory_user_token" : "false",
      "single_inventory_user" : false
    },
    "name_line1_start_index" : 2,
    "card_allocation" : 30137,
    "name_line1_end_index" : 5,
    "provider_shipping_method" : "provider_shipping_method",
    "provider_tracking_number" : "provider_tracking_number",
    "cards_processed" : 1,
    "token" : "token",
    "card_product_token" : "card_product_token",
    "card_fulfillment_time" : "2000-01-23T04:56:07.000+00:00",
    "name_line_1_numeric_postfix" : false,
    "name_line_1_random_postfix" : false,
    "expiration_offset" : {
      "unit" : "YEARS",
      "value" : 5
    },
    "fulfillment" : {
      "shipping" : {
        "care_of_line" : "care_of_line",
        "method" : "LOCAL_MAIL",
        "recipient_address" : {
          "zip" : "zip",
          "country" : "country",
          "address2" : "address2",
          "city" : "city",
          "phone" : "phone",
          "address1" : "address1",
          "last_name" : "last_name",
          "state" : "state",
          "middle_name" : "middle_name",
          "postal_code" : "postal_code",
          "first_name" : "first_name"
        }
      },
      "card_personalization" : {
        "carrier" : {
          "message_file" : "message_file",
          "logo_file" : "logo_file",
          "message_line" : "message_line",
          "template_id" : "template_id",
          "logo_thumbnail_file" : "logo_thumbnail_file"
        },
        "images" : {
          "carrier" : {
            "message_1" : "message_1",
            "name" : "name"
          },
          "signature" : {
            "name" : "name"
          },
          "carrier_return_window" : {
            "name" : "name"
          },
          "card" : {
            "name" : "name",
            "thermal_color" : "thermal_color"
          }
        },
        "text" : {
          "name_line_1" : {
            "value" : "value"
          }
        },
        "perso_type" : "EMBOSS"
      }
    },
    "provider_ship_date" : "2000-01-23T04:56:07.000+00:00"
  } ],
  "start_index" : 9,
  "count" : 0,
  "end_index" : 7
}}]
     - parameter count: (query) Number of bulk card orders to retrieve. (optional, default to 5)
     - parameter startIndex: (query) Sort order index of the first resource in the returned array. (optional, default to 0)
     - parameter sortBy: (query) Field on which to sort. Use any field in the resource model, or one of the system fields &#x60;lastModifiedTime&#x60; or &#x60;createdTime&#x60;. Prefix the field name with a hyphen (&#x60;-&#x60;) to sort in descending order. Omit the hyphen to sort in ascending order. (optional, default to -createdTime)

     - returns: RequestBuilder<BulkCardOrderListResponse> 
     */
    open class func getBulkissuancesWithRequestBuilder(count: Int? = nil, startIndex: Int? = nil, sortBy: String? = nil) -> RequestBuilder<BulkCardOrderListResponse> {
        let path = "/bulkissuances"
        let URLString = Marqeta.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "count": count?.encodeToJSON(), 
                        "start_index": startIndex?.encodeToJSON(), 
                        "sort_by": sortBy
        ])


        let requestBuilder: RequestBuilder<BulkCardOrderListResponse>.Type = Marqeta.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**
     Retrieve bulk card order

     - parameter token: (path) The unique identifier of the bulk card order to retrieve. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getBulkissuancesToken(token: String, completion: @escaping ((_ data: BulkIssuanceResponse?,_ error: Error?) -> Void)) {
        getBulkissuancesTokenWithRequestBuilder(token: token).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Retrieve bulk card order
     - GET /bulkissuances/{token}

     - BASIC:
       - type: http
       - name: mqAppAndAccessToken
     - examples: [{contentType=application/json, example={
  "created_time" : "2000-01-23T04:56:07.000+00:00",
  "expedite" : false,
  "user_association" : {
    "single_inventory_user_token" : "false",
    "single_inventory_user" : false
  },
  "name_line1_start_index" : 2,
  "card_allocation" : 30137,
  "name_line1_end_index" : 5,
  "provider_shipping_method" : "provider_shipping_method",
  "provider_tracking_number" : "provider_tracking_number",
  "cards_processed" : 1,
  "token" : "token",
  "card_product_token" : "card_product_token",
  "card_fulfillment_time" : "2000-01-23T04:56:07.000+00:00",
  "name_line_1_numeric_postfix" : false,
  "name_line_1_random_postfix" : false,
  "expiration_offset" : {
    "unit" : "YEARS",
    "value" : 5
  },
  "fulfillment" : {
    "shipping" : {
      "care_of_line" : "care_of_line",
      "method" : "LOCAL_MAIL",
      "recipient_address" : {
        "zip" : "zip",
        "country" : "country",
        "address2" : "address2",
        "city" : "city",
        "phone" : "phone",
        "address1" : "address1",
        "last_name" : "last_name",
        "state" : "state",
        "middle_name" : "middle_name",
        "postal_code" : "postal_code",
        "first_name" : "first_name"
      }
    },
    "card_personalization" : {
      "carrier" : {
        "message_file" : "message_file",
        "logo_file" : "logo_file",
        "message_line" : "message_line",
        "template_id" : "template_id",
        "logo_thumbnail_file" : "logo_thumbnail_file"
      },
      "images" : {
        "carrier" : {
          "message_1" : "message_1",
          "name" : "name"
        },
        "signature" : {
          "name" : "name"
        },
        "carrier_return_window" : {
          "name" : "name"
        },
        "card" : {
          "name" : "name",
          "thermal_color" : "thermal_color"
        }
      },
      "text" : {
        "name_line_1" : {
          "value" : "value"
        }
      },
      "perso_type" : "EMBOSS"
    }
  },
  "provider_ship_date" : "2000-01-23T04:56:07.000+00:00"
}}]
     - parameter token: (path) The unique identifier of the bulk card order to retrieve. 

     - returns: RequestBuilder<BulkIssuanceResponse> 
     */
    open class func getBulkissuancesTokenWithRequestBuilder(token: String) -> RequestBuilder<BulkIssuanceResponse> {
        var path = "/bulkissuances/{token}"
        let tokenPreEscape = "\(token)"
        let tokenPostEscape = tokenPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{token}", with: tokenPostEscape, options: .literal, range: nil)
        let URLString = Marqeta.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<BulkIssuanceResponse>.Type = Marqeta.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**
     Create bulk card order

     - parameter body: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func postBulkissuances(body: BulkIssuanceRequest? = nil, completion: @escaping ((_ data: BulkIssuanceResponse?,_ error: Error?) -> Void)) {
        postBulkissuancesWithRequestBuilder(body: body).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Create bulk card order
     - POST /bulkissuances

     - BASIC:
       - type: http
       - name: mqAppAndAccessToken
     - examples: [{contentType=application/json, example={
  "created_time" : "2000-01-23T04:56:07.000+00:00",
  "expedite" : false,
  "user_association" : {
    "single_inventory_user_token" : "false",
    "single_inventory_user" : false
  },
  "name_line1_start_index" : 2,
  "card_allocation" : 30137,
  "name_line1_end_index" : 5,
  "provider_shipping_method" : "provider_shipping_method",
  "provider_tracking_number" : "provider_tracking_number",
  "cards_processed" : 1,
  "token" : "token",
  "card_product_token" : "card_product_token",
  "card_fulfillment_time" : "2000-01-23T04:56:07.000+00:00",
  "name_line_1_numeric_postfix" : false,
  "name_line_1_random_postfix" : false,
  "expiration_offset" : {
    "unit" : "YEARS",
    "value" : 5
  },
  "fulfillment" : {
    "shipping" : {
      "care_of_line" : "care_of_line",
      "method" : "LOCAL_MAIL",
      "recipient_address" : {
        "zip" : "zip",
        "country" : "country",
        "address2" : "address2",
        "city" : "city",
        "phone" : "phone",
        "address1" : "address1",
        "last_name" : "last_name",
        "state" : "state",
        "middle_name" : "middle_name",
        "postal_code" : "postal_code",
        "first_name" : "first_name"
      }
    },
    "card_personalization" : {
      "carrier" : {
        "message_file" : "message_file",
        "logo_file" : "logo_file",
        "message_line" : "message_line",
        "template_id" : "template_id",
        "logo_thumbnail_file" : "logo_thumbnail_file"
      },
      "images" : {
        "carrier" : {
          "message_1" : "message_1",
          "name" : "name"
        },
        "signature" : {
          "name" : "name"
        },
        "carrier_return_window" : {
          "name" : "name"
        },
        "card" : {
          "name" : "name",
          "thermal_color" : "thermal_color"
        }
      },
      "text" : {
        "name_line_1" : {
          "value" : "value"
        }
      },
      "perso_type" : "EMBOSS"
    }
  },
  "provider_ship_date" : "2000-01-23T04:56:07.000+00:00"
}}]
     - parameter body: (body)  (optional)

     - returns: RequestBuilder<BulkIssuanceResponse> 
     */
    open class func postBulkissuancesWithRequestBuilder(body: BulkIssuanceRequest? = nil) -> RequestBuilder<BulkIssuanceResponse> {
        let path = "/bulkissuances"
        let URLString = Marqeta.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<BulkIssuanceResponse>.Type = Marqeta.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
}
