//
// BusinessTransitionsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class BusinessTransitionsAPI {
    /**
     List business transitions

     - parameter businessToken: (path) Unique identifier of the business resource associated with the transitions to retrieve. 
     - parameter count: (query) Number of business transitions to retrieve. (optional, default to 5)
     - parameter startIndex: (query) Sort order index of the first resource in the returned array. (optional, default to 0)
     - parameter fields: (query) Comma-delimited list of fields to return (&#x60;field_1,field_2&#x60;, and so on). Leave blank to return all fields. (optional)
     - parameter sortBy: (query) Field on which to sort. Use any field in the resource model, or one of the system fields &#x60;lastModifiedTime&#x60; or &#x60;createdTime&#x60;. Prefix the field name with a hyphen (&#x60;-&#x60;) to sort in descending order. Omit the hyphen to sort in ascending order. (optional, default to -id)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getBusinesstransitionsBusinessBusinesstoken(businessToken: String, count: Int? = nil, startIndex: Int? = nil, fields: String? = nil, sortBy: String? = nil, completion: @escaping ((_ data: BusinessTransitionListResponse?,_ error: Error?) -> Void)) {
        getBusinesstransitionsBusinessBusinesstokenWithRequestBuilder(businessToken: businessToken, count: count, startIndex: startIndex, fields: fields, sortBy: sortBy).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     List business transitions
     - GET /businesstransitions/business/{business_token}

     - BASIC:
       - type: http
       - name: mqAppAndAccessToken
     - examples: [{contentType=application/json, example={
  "is_more" : false,
  "data" : [ {
    "reason_code" : "00",
    "created_time" : "2000-01-23T04:56:07.000+00:00",
    "reason" : "reason",
    "business_token" : "business_token",
    "last_modified_time" : "2000-01-23T04:56:07.000+00:00",
    "channel" : "API",
    "status" : "UNVERIFIED",
    "token" : "token"
  }, {
    "reason_code" : "00",
    "created_time" : "2000-01-23T04:56:07.000+00:00",
    "reason" : "reason",
    "business_token" : "business_token",
    "last_modified_time" : "2000-01-23T04:56:07.000+00:00",
    "channel" : "API",
    "status" : "UNVERIFIED",
    "token" : "token"
  } ],
  "start_index" : 1,
  "count" : 0,
  "end_index" : 6
}}]
     - parameter businessToken: (path) Unique identifier of the business resource associated with the transitions to retrieve. 
     - parameter count: (query) Number of business transitions to retrieve. (optional, default to 5)
     - parameter startIndex: (query) Sort order index of the first resource in the returned array. (optional, default to 0)
     - parameter fields: (query) Comma-delimited list of fields to return (&#x60;field_1,field_2&#x60;, and so on). Leave blank to return all fields. (optional)
     - parameter sortBy: (query) Field on which to sort. Use any field in the resource model, or one of the system fields &#x60;lastModifiedTime&#x60; or &#x60;createdTime&#x60;. Prefix the field name with a hyphen (&#x60;-&#x60;) to sort in descending order. Omit the hyphen to sort in ascending order. (optional, default to -id)

     - returns: RequestBuilder<BusinessTransitionListResponse> 
     */
    open class func getBusinesstransitionsBusinessBusinesstokenWithRequestBuilder(businessToken: String, count: Int? = nil, startIndex: Int? = nil, fields: String? = nil, sortBy: String? = nil) -> RequestBuilder<BusinessTransitionListResponse> {
        var path = "/businesstransitions/business/{business_token}"
        let businessTokenPreEscape = "\(businessToken)"
        let businessTokenPostEscape = businessTokenPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{business_token}", with: businessTokenPostEscape, options: .literal, range: nil)
        let URLString = Marqeta.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "count": count?.encodeToJSON(), 
                        "start_index": startIndex?.encodeToJSON(), 
                        "fields": fields, 
                        "sort_by": sortBy
        ])


        let requestBuilder: RequestBuilder<BusinessTransitionListResponse>.Type = Marqeta.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**
     Retrieve business transition

     - parameter token: (path) The unique identifier of the business transition you want to retrieve. 
     - parameter fields: (query) Field on which to sort. Use any field in the resource model, or one of the system fields &#x60;lastModifiedTime&#x60; or &#x60;createdTime&#x60;. Prefix the field name with a hyphen (&#x60;-&#x60;) to sort in descending order. Omit the hyphen to sort in ascending order. (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getBusinesstransitionsToken(token: String, fields: String? = nil, completion: @escaping ((_ data: BusinessTransitionResponse?,_ error: Error?) -> Void)) {
        getBusinesstransitionsTokenWithRequestBuilder(token: token, fields: fields).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Retrieve business transition
     - GET /businesstransitions/{token}

     - BASIC:
       - type: http
       - name: mqAppAndAccessToken
     - examples: [{contentType=application/json, example={
  "reason_code" : "00",
  "created_time" : "2000-01-23T04:56:07.000+00:00",
  "reason" : "reason",
  "business_token" : "business_token",
  "last_modified_time" : "2000-01-23T04:56:07.000+00:00",
  "channel" : "API",
  "status" : "UNVERIFIED",
  "token" : "token"
}}]
     - parameter token: (path) The unique identifier of the business transition you want to retrieve. 
     - parameter fields: (query) Field on which to sort. Use any field in the resource model, or one of the system fields &#x60;lastModifiedTime&#x60; or &#x60;createdTime&#x60;. Prefix the field name with a hyphen (&#x60;-&#x60;) to sort in descending order. Omit the hyphen to sort in ascending order. (optional)

     - returns: RequestBuilder<BusinessTransitionResponse> 
     */
    open class func getBusinesstransitionsTokenWithRequestBuilder(token: String, fields: String? = nil) -> RequestBuilder<BusinessTransitionResponse> {
        var path = "/businesstransitions/{token}"
        let tokenPreEscape = "\(token)"
        let tokenPostEscape = tokenPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{token}", with: tokenPostEscape, options: .literal, range: nil)
        let URLString = Marqeta.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "fields": fields
        ])


        let requestBuilder: RequestBuilder<BusinessTransitionResponse>.Type = Marqeta.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**
     Create business transition

     - parameter body: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func postBusinesstransitions(body: BusinessTransitionRequest? = nil, completion: @escaping ((_ data: BusinessTransitionResponse?,_ error: Error?) -> Void)) {
        postBusinesstransitionsWithRequestBuilder(body: body).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Create business transition
     - POST /businesstransitions

     - BASIC:
       - type: http
       - name: mqAppAndAccessToken
     - examples: [{contentType=application/json, example={
  "reason_code" : "00",
  "created_time" : "2000-01-23T04:56:07.000+00:00",
  "reason" : "reason",
  "business_token" : "business_token",
  "last_modified_time" : "2000-01-23T04:56:07.000+00:00",
  "channel" : "API",
  "status" : "UNVERIFIED",
  "token" : "token"
}}]
     - parameter body: (body)  (optional)

     - returns: RequestBuilder<BusinessTransitionResponse> 
     */
    open class func postBusinesstransitionsWithRequestBuilder(body: BusinessTransitionRequest? = nil) -> RequestBuilder<BusinessTransitionResponse> {
        let path = "/businesstransitions"
        let URLString = Marqeta.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<BusinessTransitionResponse>.Type = Marqeta.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
}
