//
// AccountStatusEnum.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Status of the credit account.  *NOTE* &#x60;CHARGE_OFF&#x60; is not an allowable value for &#x60;original_status&#x60;. */
public enum AccountStatusEnum: String, Codable {
    case unactivated = "UNACTIVATED"
    case active = "ACTIVE"
    case suspended = "SUSPENDED"
    case terminated = "TERMINATED"
    case chargeOff = "CHARGE_OFF"
}