//
// AccountUpdateReqCreditLimit.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Contains information on the credit limit. */

public struct AccountUpdateReqCreditLimit: Codable {

    /** Maximum balance the credit account can carry. */
    public var value: Decimal

    public init(value: Decimal) {
        self.value = value
    }


}
