//
// AccountAdjustmentResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import AnyCodable

/** Contains information returned for account adjustment. */

public struct AccountAdjustmentResponse: Codable {

    public enum Reason: String, Codable { 
        case dispute = "DISPUTE"
        case disputeResolution = "DISPUTE_RESOLUTION"
        case returnedOrCanceledPayment = "RETURNED_OR_CANCELED_PAYMENT"
        case other = "OTHER"
    }
    public enum ModelType: String, Codable { 
        case purchase = "PURCHASE"
        case fee = "FEE"
        case reward = "REWARD"
        case interest = "INTEREST"
        case general = "GENERAL"
    }
    /** Unique identifier of the credit account on which the adjustment was made. */
    public var accountToken: String
    /** Contains the adjustment&#x27;s full details.  The fields returned in this object depend on the adjustment type.  Interest returns interest details. For the specific fields returned, see the &#x60;detail_object&#x60; fields marked \&quot;Returned for interest journal entries\&quot; in the &lt;&lt;/core-api/credit-account-journal-entries#getAccountJournalEntry, account journal entry response fields&gt;&gt;.  Disputes return dispute details. For the specific fields returned, see the &lt;&lt;/core-api/credit-disputes#retrieveDispute, dispute response fields&gt;&gt;. */
    public var adjustmentDetailObject: AnyCodable?
    /** Amount of the adjustment. */
    public var amount: Decimal
    /** Date and time when the account adjustment was applied, in UTC. */
    public var createdTime: Date?
    public var currencyCode: CurrencyCode
    /** Description of the adjustment. */
    public var _description: String
    /** Unique identifier of the adjustment detail. For example, the token of the dispute, the interest charge, or the returned payment that prompted the adjustment.  Returned when the system automatically applies an adjustment. */
    public var detailToken: String?
    /** Unique identifier you provide of an associated external adjustment that exists outside Marqeta&#x27;s credit platform. */
    public var externalAdjustmentId: UUID?
    /** Additional information on the adjustment. */
    public var note: String?
    /** Unique identifier of the original journal entry needing the adjustment. */
    public var originalLedgerEntryToken: UUID?
    /** Reason for the adjustment.  * &#x60;DISPUTE&#x60; - The adjustment occurred because a dispute was initiated. * &#x60;DISPUTE_RESOLUTION&#x60; - The adjustment occurred because of the result of a dispute resolution. * &#x60;RETURNED_OR_CANCELED_PAYMENT&#x60; - The adjustment occurred because a payment was returned or canceled. * &#x60;OTHER&#x60; - Any other reason the adjustment occurred. For example, a waived fee. */
    public var reason: Reason
    /** Contains full details of the related dispute or returned payment.  The fields returned in this object depend on whether a dispute or returned payment led to the interest adjustment. A dispute returns dispute details; a returned payment returns payment details.  For more on the dispute details returned, see the &lt;&lt;/core-api/credit-disputes#retrieveDispute, dispute response fields&gt;&gt;.  For more on the returned payment details returned, see the &lt;&lt;/core-api/credit-account-payments#retrievePayment, payment response fields&gt;&gt;.  This field is returned for interest adjustments only. */
    public var relatedDetailObject: AnyCodable?
    /** Unique identifier of the dispute or returned payment that prompted the interest adjustment.  This field is returned for interest adjustments only. */
    public var relatedDetailToken: String?
    /** Unique identifier of the adjustment.  If in the &#x60;detail_object&#x60;, unique identifier of the detail object. */
    public var token: String
    /** Type of adjustment.  The adjustment is made on its correlating amount (for example, purchase adjustments are made on purchase amounts). You can use general adjustments for standalone adjustments made on the credit account balance itself, which includes account write-offs, credits, and more. */
    public var type: ModelType

    public init(accountToken: String, adjustmentDetailObject: AnyCodable? = nil, amount: Decimal, createdTime: Date? = nil, currencyCode: CurrencyCode, _description: String, detailToken: String? = nil, externalAdjustmentId: UUID? = nil, note: String? = nil, originalLedgerEntryToken: UUID? = nil, reason: Reason, relatedDetailObject: AnyCodable? = nil, relatedDetailToken: String? = nil, token: String, type: ModelType) {
        self.accountToken = accountToken
        self.adjustmentDetailObject = adjustmentDetailObject
        self.amount = amount
        self.createdTime = createdTime
        self.currencyCode = currencyCode
        self._description = _description
        self.detailToken = detailToken
        self.externalAdjustmentId = externalAdjustmentId
        self.note = note
        self.originalLedgerEntryToken = originalLedgerEntryToken
        self.reason = reason
        self.relatedDetailObject = relatedDetailObject
        self.relatedDetailToken = relatedDetailToken
        self.token = token
        self.type = type
    }

    public enum CodingKeys: String, CodingKey { 
        case accountToken = "account_token"
        case adjustmentDetailObject = "adjustment_detail_object"
        case amount
        case createdTime = "created_time"
        case currencyCode = "currency_code"
        case _description = "description"
        case detailToken = "detail_token"
        case externalAdjustmentId = "external_adjustment_id"
        case note
        case originalLedgerEntryToken = "original_ledger_entry_token"
        case reason
        case relatedDetailObject = "related_detail_object"
        case relatedDetailToken = "related_detail_token"
        case token
        case type
    }

}
