//
// AddressVerification.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Contains address verification information. */

public struct AddressVerification: Codable {

    /** Name of the cardholder. */
    public var name: String?
    /** Postal code. */
    public var postalCode: String?
    /** Street address provided by the cardholder. */
    public var streetAddress: String?
    /** United States ZIP code. */
    public var zip: String?

    public init(name: String? = nil, postalCode: String? = nil, streetAddress: String? = nil, zip: String? = nil) {
        self.name = name
        self.postalCode = postalCode
        self.streetAddress = streetAddress
        self.zip = zip
    }

    public enum CodingKeys: String, CodingKey { 
        case name
        case postalCode = "postal_code"
        case streetAddress = "street_address"
        case zip
    }

}
