//
// Airline.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Contains information about airline-related transactions. */

public struct Airline: Codable {

    /** The date and time of departure. */
    public var departDate: Date?
    /** The city where the flight originates. */
    public var originationCity: String?
    /** The name of the passenger. */
    public var passengerName: String?

    public init(departDate: Date? = nil, originationCity: String? = nil, passengerName: String? = nil) {
        self.departDate = departDate
        self.originationCity = originationCity
        self.passengerName = passengerName
    }

    public enum CodingKeys: String, CodingKey { 
        case departDate = "depart_date"
        case originationCity = "origination_city"
        case passengerName = "passenger_name"
    }

}
