//
// ApplicationOfCredits.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Contains information on the cycle type and billing cycle day when credits are applied in the daily balance calculation. */

public struct ApplicationOfCredits: Codable {

    public var cycleType: CycleType
    /** Day of the billing cycle when credits are applied. */
    public var day: Int

    public init(cycleType: CycleType, day: Int) {
        self.cycleType = cycleType
        self.day = day
    }

    public enum CodingKeys: String, CodingKey { 
        case cycleType = "cycle_type"
        case day
    }

}
