//
// ApplicationResourceState.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** State of the application.  If manually &lt;&lt;/core-api/credit-applications#transitionApplication, transitioning an application state&gt;&gt;:  * &#x60;application_state&#x60; is the state to which you want to transition the application status; must be &#x60;ACCEPTED&#x60; or &#x60;REJECTED&#x60;. * &#x60;original_status&#x60; returns the state of the application before it was manually transitioned. * &#x60;status&#x60; returns the state to which the application was transitioned. */
public enum ApplicationResourceState: String, Codable {
    case created = "CREATED"
    case decisioning = "DECISIONING"
    case manualReview = "MANUAL_REVIEW"
    case expired = "EXPIRED"
    case approved = "APPROVED"
    case rejected = "REJECTED"
    case accepted = "ACCEPTED"
    case declined = "DECLINED"
    case error = "ERROR"
}