//
// AprScheduleResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AprScheduleResponse: Codable {

    /** Whether the APR is active. */
    public var active: Bool?
    /** Date and time when the APR was created on Marqeta&#x27;s credit platform, in UTC. */
    public var createdDate: Date?
    /** Contains one or more &#x60;schedule&#x60; objects, which contain information about the annual percentage rates (APRs) associated with the type of balance on the credit account and when they are effective. */
    public var schedule: [AprScheduleEntryResponse]
    public var type: AccountAprType
    /** Date and time when the APR was last updated on Marqeta&#x27;s credit platform, in UTC. */
    public var updatedDate: Date?

    public init(active: Bool? = nil, createdDate: Date? = nil, schedule: [AprScheduleEntryResponse], type: AccountAprType, updatedDate: Date? = nil) {
        self.active = active
        self.createdDate = createdDate
        self.schedule = schedule
        self.type = type
        self.updatedDate = updatedDate
    }

    public enum CodingKeys: String, CodingKey { 
        case active
        case createdDate = "created_date"
        case schedule
        case type
        case updatedDate = "updated_date"
    }

}
