//
// AuthorizationControls.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Controls the expiration of authorizations and automatic increases to the authorization amount for MCCs specified in this group.  By default, these authorization controls apply program-wide, meaning that they apply to every card in your program. You can, however, exempt cards associated with any particular card product by setting that card product&#x27;s &#x60;allow_mcc_group_authorization_controls&#x60; field to &#x60;false&#x60;. */

public struct AuthorizationControls: Codable {

    /** Specifies the number of days after which an authorization associated with this group expires. */
    public var holdExpirationDays: Int?
    public var holdIncrease: HoldIncrease?

    public init(holdExpirationDays: Int? = nil, holdIncrease: HoldIncrease? = nil) {
        self.holdExpirationDays = holdExpirationDays
        self.holdIncrease = holdIncrease
    }

    public enum CodingKeys: String, CodingKey { 
        case holdExpirationDays = "hold_expiration_days"
        case holdIncrease = "hold_increase"
    }

}
