//
// BillingAddress.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct BillingAddress: Codable {

    public var address: String?
    public var compressedZip: String?
    public var firstName: String?
    public var lastName: String?
    public var zip: String?

    public init(address: String? = nil, compressedZip: String? = nil, firstName: String? = nil, lastName: String? = nil, zip: String? = nil) {
        self.address = address
        self.compressedZip = compressedZip
        self.firstName = firstName
        self.lastName = lastName
        self.zip = zip
    }

    public enum CodingKeys: String, CodingKey { 
        case address
        case compressedZip = "compressed_zip"
        case firstName = "first_name"
        case lastName = "last_name"
        case zip
    }

}
