//
// CardMetadata.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CardMetadata: Codable {

    /** Associates customer-injected metadata with the card. */
    public var metadata: [String:String]?

    public init(metadata: [String:String]? = nil) {
        self.metadata = metadata
    }


}
