//
// CardHolderAddressUpdateModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CardHolderAddressUpdateModel: Codable {

    /** Specifies whether the address is active. */
    public var active: Bool?
    /** Street address. */
    public var address1: String?
    /** Additional address information. */
    public var address2: String?
    /** City of the address. */
    public var city: String?
    /** Country of the address. */
    public var country: String?
    /** First name of the account holder. */
    public var firstName: String?
    /** A value of &#x60;true&#x60; specifies that this address is the default address used by the account holder&#x27;s funding source. If this is the account holder&#x27;s only address, it is used as the default regardless of this field&#x27;s setting. */
    public var isDefaultAddress: Bool?
    /** Last name of the account holder. */
    public var lastName: String?
    /** Telephone number of the account holder. */
    public var phone: String?
    /** Postal code of the address. */
    public var postalCode: String?
    /** Two-character state, province, or territorial abbreviation.  For a complete list, see &lt;&lt;/core-api/kyc-verification#_valid_state_provincial_and_territorial_abbreviations, Valid state, provincial, and territorial abbreviations&gt;&gt;. */
    public var state: String?
    /** United States ZIP code of the address. */
    public var zip: String?

    public init(active: Bool? = nil, address1: String? = nil, address2: String? = nil, city: String? = nil, country: String? = nil, firstName: String? = nil, isDefaultAddress: Bool? = nil, lastName: String? = nil, phone: String? = nil, postalCode: String? = nil, state: String? = nil, zip: String? = nil) {
        self.active = active
        self.address1 = address1
        self.address2 = address2
        self.city = city
        self.country = country
        self.firstName = firstName
        self.isDefaultAddress = isDefaultAddress
        self.lastName = lastName
        self.phone = phone
        self.postalCode = postalCode
        self.state = state
        self.zip = zip
    }

    public enum CodingKeys: String, CodingKey { 
        case active
        case address1 = "address_1"
        case address2 = "address_2"
        case city
        case country
        case firstName = "first_name"
        case isDefaultAddress = "is_default_address"
        case lastName = "last_name"
        case phone
        case postalCode = "postal_code"
        case state
        case zip
    }

}
