//
// CardUpdateRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CardUpdateRequest: Codable {

    /** Set to &#x60;true&#x60; to request expedited processing of the card by your card fulfillment provider.  This expedited service is available for cards fulfilled by link:http://perfectplastic.com/[Perfect Plastic Printing, window&#x3D;\&quot;_blank\&quot;], link:http://www.idemia.com[IDEMIA, window&#x3D;\&quot;_blank\&quot;], and link:https://www.arroweye.com/[Arroweye Solutions, window&#x3D;\&quot;_blank\&quot;].  *NOTE:* Contact your Marqeta representative for information regarding the cost of expedited service. */
    public var expedite: Bool?
    public var fulfillment: CardFulfillmentRequest?
    /** Associates customer-provided metadata with the card. */
    public var metadata: [String:String]?
    /** Unique identifier of the card you want to update. */
    public var token: String
    /** Specifies the user you want to associate with the card. */
    public var userToken: String?

    public init(expedite: Bool? = nil, fulfillment: CardFulfillmentRequest? = nil, metadata: [String:String]? = nil, token: String, userToken: String? = nil) {
        self.expedite = expedite
        self.fulfillment = fulfillment
        self.metadata = metadata
        self.token = token
        self.userToken = userToken
    }

    public enum CodingKeys: String, CodingKey { 
        case expedite
        case fulfillment
        case metadata
        case token
        case userToken = "user_token"
    }

}
