//
// ClearingAndSettlement.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Specifies the destination for overdraft funds. */

public struct ClearingAndSettlement: Codable {

    public enum OverdraftDestination: String, Codable { 
        case gpa = "GPA"
        case msa = "MSA"
        case merchantCampaignAccount = "MERCHANT_CAMPAIGN_ACCOUNT"
        case globalOverdraftAccount = "GLOBAL_OVERDRAFT_ACCOUNT"
    }
    /** Specifies the destination for overdraft funds.  This field does not apply if JIT Funding is enabled. */
    public var overdraftDestination: OverdraftDestination?

    public init(overdraftDestination: OverdraftDestination? = nil) {
        self.overdraftDestination = overdraftDestination
    }

    public enum CodingKeys: String, CodingKey { 
        case overdraftDestination = "overdraft_destination"
    }

}
