//
// ConfigFeeScheduleReq.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Contains information relevant to configuring fees. */

public struct ConfigFeeScheduleReq: Codable {

    /** Contains one or more fee schedules. */
    public var schedule: [ConfigFeeScheduleEntry]
    public var type: AccountProductFeeType

    public init(schedule: [ConfigFeeScheduleEntry], type: AccountProductFeeType) {
        self.schedule = schedule
        self.type = type
    }


}
