//
// DelinquencyStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Delinquency status of an account. */
public enum DelinquencyStatus: String, Codable {
    case current = "CURRENT"
    case delinquent = "DELINQUENT"
}