//
// DelinquencyTransitionTriggerReason.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Event that triggered an update to the account&#x27;s delinquency state. */
public enum DelinquencyTransitionTriggerReason: String, Codable {
    case payment = "PAYMENT"
    case paymentVoid = "PAYMENT_VOID"
    case credit = "CREDIT"
    case minimumPaymentOverride = "MINIMUM_PAYMENT_OVERRIDE"
    case statementGeneration = "STATEMENT_GENERATION"
    case reage = "REAGE"
}