//
// DepositAccount.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DepositAccount: Codable {

    public var accountNumber: String
    public var allowImmediateCredit: Bool?
    public var businessToken: String?
    public var routingNumber: String
    public var token: String
    public var userToken: String?

    public init(accountNumber: String, allowImmediateCredit: Bool? = nil, businessToken: String? = nil, routingNumber: String, token: String, userToken: String? = nil) {
        self.accountNumber = accountNumber
        self.allowImmediateCredit = allowImmediateCredit
        self.businessToken = businessToken
        self.routingNumber = routingNumber
        self.token = token
        self.userToken = userToken
    }

    public enum CodingKeys: String, CodingKey { 
        case accountNumber = "account_number"
        case allowImmediateCredit = "allow_immediate_credit"
        case businessToken = "business_token"
        case routingNumber = "routing_number"
        case token
        case userToken = "user_token"
    }

}
