//
// DigitalWalletTokenHash.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Contains identifiers of the digital wallet token resource and the card resource. */

public struct DigitalWalletTokenHash: Codable {

    /** Unique identifier of the card resource to use for the provisioning request. */
    public var cardToken: String?
    /** Unique identifier of the digital wallet token resource. */
    public var token: String

    public init(cardToken: String? = nil, token: String) {
        self.cardToken = cardToken
        self.token = token
    }

    public enum CodingKeys: String, CodingKey { 
        case cardToken = "card_token"
        case token
    }

}
