//
// DirectDepositAccountRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DirectDepositAccountRequest: Codable {

    public enum ModelType: String, Codable { 
        case depositAccount = "DEPOSIT_ACCOUNT"
        case checking = "CHECKING"
        case savings = "SAVINGS"
        case interestBearing = "INTEREST_BEARING"
    }
    public var allowImmediateCredit: Bool?
    /** Required if &#x27;user_token&#x27; is null */
    public var businessToken: String?
    /** Required if account type &#x3D; Checking */
    public var customerDueDiligence: [CustomerDueDiligenceRequest]?
    public var token: String?
    public var type: ModelType?
    /** Required if &#x27;business_token&#x27; is null */
    public var userToken: String?

    public init(allowImmediateCredit: Bool? = nil, businessToken: String? = nil, customerDueDiligence: [CustomerDueDiligenceRequest]? = nil, token: String? = nil, type: ModelType? = nil, userToken: String? = nil) {
        self.allowImmediateCredit = allowImmediateCredit
        self.businessToken = businessToken
        self.customerDueDiligence = customerDueDiligence
        self.token = token
        self.type = type
        self.userToken = userToken
    }

    public enum CodingKeys: String, CodingKey { 
        case allowImmediateCredit = "allow_immediate_credit"
        case businessToken = "business_token"
        case customerDueDiligence = "customer_due_diligence"
        case token
        case type
        case userToken = "user_token"
    }

}
