//
// DisputeModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Contains information about a disputed transaction. */

public struct DisputeModel: Codable {

    /** The unique identifier of the dispute case. */
    public var caseManagementIdentifier: String?
    /** The reason for the dispute. */
    public var reason: String?

    public init(caseManagementIdentifier: String? = nil, reason: String? = nil) {
        self.caseManagementIdentifier = caseManagementIdentifier
        self.reason = reason
    }

    public enum CodingKeys: String, CodingKey { 
        case caseManagementIdentifier = "case_management_identifier"
        case reason
    }

}
