//
// EchoPingRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct EchoPingRequest: Codable {

    /** Payload of the ping request. */
    public var payload: String?
    /** Unique identifier of the ping request. */
    public var token: String?

    public init(payload: String? = nil, token: String? = nil) {
        self.payload = payload
        self.token = token
    }


}
