//
// FeeTransferRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FeeTransferRequest: Codable {

    /** Specifies the business account holder to which the fee applies.  Pass either &#x60;business_token&#x60; or &#x60;user_token&#x60;, not both. */
    public var businessToken: String
    /** Contains attributes that define characteristics of one or more fees. */
    public var fees: [FeeModel]
    /** Metadata about the transfer. */
    public var tags: String?
    /** Unique identifier of the fee transfer.  If you do not include a token, the system will generate one automatically. This token is necessary for use in other API calls, so we recommend that rather than let the system generate one, you use a simple string that is easy to remember. This value cannot be updated. */
    public var token: String?
    /** Specifies the user account holder to which the fee applies.  Pass either &#x60;user_token&#x60; or &#x60;business_token&#x60;, not both. */
    public var userToken: String

    public init(businessToken: String, fees: [FeeModel], tags: String? = nil, token: String? = nil, userToken: String) {
        self.businessToken = businessToken
        self.fees = fees
        self.tags = tags
        self.token = token
        self.userToken = userToken
    }

    public enum CodingKeys: String, CodingKey { 
        case businessToken = "business_token"
        case fees
        case tags
        case token
        case userToken = "user_token"
    }

}
