//
// GpaResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Contains information about a GPA order, including fees, funding sources, and addresses. See &lt;&lt;/core-api/gpa-orders, GPA Orders&gt;&gt; for more information. */

public struct GpaResponse: Codable {

    /** Amount funded. */
    public var amount: Decimal
    /** Unique identifier of the business.  This field is returned if it exists in the resource. */
    public var businessToken: String?
    /** Date and time when the GPA order was created, in UTC. */
    public var createdTime: Date
    /** Three-digit ISO 4217 currency code. */
    public var currencyCode: String
    /** List of fees associated with the funding transaction.  This array is returned if it exists in the resource. */
    public var fees: [FeeDetail]?
    public var funding: Funding
    /** Unique identifier of the funding source address to use for this order. */
    public var fundingSourceAddressToken: String?
    /** Unique identifier of the funding source to use for this order. */
    public var fundingSourceToken: String
    /** Message about the status of the funding request. Useful for determining whether it was approved and completed successfully, declined by the gateway, or timed out.  This field is returned if it exists in the resource. */
    public var gatewayMessage: String?
    /** Unique identifier of the JIT Funding request and response.  This field is returned if it exists in the resource. */
    public var gatewayToken: Int64?
    public var jitFunding: JitFundingApi?
    /** Date and time when the GPA order was last modified, in UTC. */
    public var lastModifiedTime: Date
    /** Additional descriptive text.  This field is returned if it exists in the resource. */
    public var memo: String?
    public var response: ModelResponse
    /** Current status of the funding transaction. */
    public var state: String
    /** Comma-delimited list of tags describing the order.  This field is returned if it exists in the resource. */
    public var tags: String?
    /** Unique identifier of the GPA order. */
    public var token: String
    /** Unique identifier of the transaction being funded. */
    public var transactionToken: String
    /** Unique identifier of the user resource.  This field is returned if it exists in the resource. */
    public var userToken: String?

    public init(amount: Decimal, businessToken: String? = nil, createdTime: Date, currencyCode: String, fees: [FeeDetail]? = nil, funding: Funding, fundingSourceAddressToken: String? = nil, fundingSourceToken: String, gatewayMessage: String? = nil, gatewayToken: Int64? = nil, jitFunding: JitFundingApi? = nil, lastModifiedTime: Date, memo: String? = nil, response: ModelResponse, state: String, tags: String? = nil, token: String, transactionToken: String, userToken: String? = nil) {
        self.amount = amount
        self.businessToken = businessToken
        self.createdTime = createdTime
        self.currencyCode = currencyCode
        self.fees = fees
        self.funding = funding
        self.fundingSourceAddressToken = fundingSourceAddressToken
        self.fundingSourceToken = fundingSourceToken
        self.gatewayMessage = gatewayMessage
        self.gatewayToken = gatewayToken
        self.jitFunding = jitFunding
        self.lastModifiedTime = lastModifiedTime
        self.memo = memo
        self.response = response
        self.state = state
        self.tags = tags
        self.token = token
        self.transactionToken = transactionToken
        self.userToken = userToken
    }

    public enum CodingKeys: String, CodingKey { 
        case amount
        case businessToken = "business_token"
        case createdTime = "created_time"
        case currencyCode = "currency_code"
        case fees
        case funding
        case fundingSourceAddressToken = "funding_source_address_token"
        case fundingSourceToken = "funding_source_token"
        case gatewayMessage = "gateway_message"
        case gatewayToken = "gateway_token"
        case jitFunding = "jit_funding"
        case lastModifiedTime = "last_modified_time"
        case memo
        case response
        case state
        case tags
        case token
        case transactionToken = "transaction_token"
        case userToken = "user_token"
    }

}
