//
// ManualEntry.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ManualEntry: Codable {

    public var addressVerification: DigitalWalletTokenAddressVerification?
    /** Specifies if manual entry is enabled. */
    public var enabled: Bool?

    public init(addressVerification: DigitalWalletTokenAddressVerification? = nil, enabled: Bool? = nil) {
        self.addressVerification = addressVerification
        self.enabled = enabled
    }

    public enum CodingKeys: String, CodingKey { 
        case addressVerification = "address_verification"
        case enabled
    }

}
