//
// MerchantGroupUpdateRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MerchantGroupUpdateRequest: Codable {

    /** Indicates if the merchant group is active or not. */
    public var active: Bool?
    /** Comma-separated list of alphanumeric merchant identifiers. You can include merchant identifiers in multiple merchant groups. */
    public var mids: [String]?
    /** Name of the merchant group. */
    public var name: String?

    public init(active: Bool? = nil, mids: [String]? = nil, name: String? = nil) {
        self.active = active
        self.mids = mids
        self.name = name
    }


}
