//
// Method.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Method, either a flat amount or a percentage.  *NOTE:* Only &#x60;FLAT&#x60; is currently supported. */
public enum Method: String, Codable {
    case percentage = "PERCENTAGE"
    case flat = "FLAT"
}