//
// MoneyInTransaction.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Defines the original credit transaction (OCT) types that are subject to velocity control. */

public struct MoneyInTransaction: Codable {

    /** Specifies the types of credits to include in the original credit transaction (OCT). */
    public var includeCreditsTypes: [String]?
    /** Indicates whether or not cash and check network load transactions will be subject to velocity control. */
    public var includeNetworkLoadTypes: [String]?

    public init(includeCreditsTypes: [String]? = nil, includeNetworkLoadTypes: [String]? = nil) {
        self.includeCreditsTypes = includeCreditsTypes
        self.includeNetworkLoadTypes = includeNetworkLoadTypes
    }

    public enum CodingKeys: String, CodingKey { 
        case includeCreditsTypes = "include_credits_types"
        case includeNetworkLoadTypes = "include_network_load_types"
    }

}
