//
// NetworkFeeModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Contains card network fees assessed against the cardholder. */

public struct NetworkFeeModel: Codable {

    public enum CreditDebit: String, Codable { 
        case c = "C"
        case d = "D"
    }
    public enum ModelType: String, Codable { 
        case issuerFee = "ISSUER_FEE"
        case switchFee = "SWITCH_FEE"
        case pindebitAssocFee = "PINDEBIT_ASSOC_FEE"
        case acquirerFee = "ACQUIRER_FEE"
        case interchangeFee = "INTERCHANGE_FEE"
        case curConvCardholderFee = "CUR_CONV_CARDHOLDER_FEE"
        case curConvIssuerFee = "CUR_CONV_ISSUER_FEE"
        case crossBorderIssuerFee = "CROSS_BORDER_ISSUER_FEE"
    }
    /** The amount of the network fee. */
    public var amount: Decimal?
    /** Indicates whether the fee is a credit or a debit.  * *C* indicates a credit * *D* indicates a debit */
    public var creditDebit: CreditDebit?
    /** The type of fee assessed by the card network. */
    public var type: ModelType?

    public init(amount: Decimal? = nil, creditDebit: CreditDebit? = nil, type: ModelType? = nil) {
        self.amount = amount
        self.creditDebit = creditDebit
        self.type = type
    }

    public enum CodingKeys: String, CodingKey { 
        case amount
        case creditDebit = "credit_debit"
        case type
    }

}
