//
// PaymentTransitionResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Response containing payment transition information. */

public struct PaymentTransitionResponse: Codable {

    /** Unique identifier of the credit account on which you want to transition a payment status. */
    public var accountToken: String
    /** Date and time when the payment transition was created on Marqeta&#x27;s credit platform, in UTC. */
    public var createdTime: Date?
    /** Unique identifier of the payment whose status you want to transition. */
    public var paymentToken: String
    public var status: PaymentStatus
    /** Unique identifier of the payment status transition. */
    public var token: String

    public init(accountToken: String, createdTime: Date? = nil, paymentToken: String, status: PaymentStatus, token: String) {
        self.accountToken = accountToken
        self.createdTime = createdTime
        self.paymentToken = paymentToken
        self.status = status
        self.token = token
    }

    public enum CodingKeys: String, CodingKey { 
        case accountToken = "account_token"
        case createdTime = "created_time"
        case paymentToken = "payment_token"
        case status
        case token
    }

}
