//
// PaymentCreateReq.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Created when a user pays a portion or all of their statement balance. This is for immediate payments only; Once set to &#x60;ACTIVE&#x60;, cannot be edited or deleted. */

public struct PaymentCreateReq: Codable {

    public enum Method: String, Codable { 
        case ach = "ACH"
        case check = "CHECK"
        case debit = "DEBIT"
        case cash = "CASH"
    }
    /** Amount of the payment. */
    public var amount: Decimal
    public var currencyCode: CurrencyCode
    /** Description of the payment. */
    public var _description: String
    /** Date and time when the payment impacts the account balance and fee calculations. */
    public var impactTime: Date?
    /** Customer-defined additional information about the payment (for example, a check number). */
    public var metadata: String?
    /** Method of payment. */
    public var method: Method
    /** Unique identifier of the payment source. Required for ACH payments. */
    public var paymentSourceToken: String?
    /** Unique identifier of the payment. */
    public var token: String?

    public init(amount: Decimal, currencyCode: CurrencyCode, _description: String, impactTime: Date? = nil, metadata: String? = nil, method: Method, paymentSourceToken: String? = nil, token: String? = nil) {
        self.amount = amount
        self.currencyCode = currencyCode
        self._description = _description
        self.impactTime = impactTime
        self.metadata = metadata
        self.method = method
        self.paymentSourceToken = paymentSourceToken
        self.token = token
    }

    public enum CodingKeys: String, CodingKey { 
        case amount
        case currencyCode = "currency_code"
        case _description = "description"
        case impactTime = "impact_time"
        case metadata
        case method
        case paymentSourceToken = "payment_source_token"
        case token
    }

}
