//
// PeerTransferResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Contains information about a peer transfer, including sender and recipient tokens, transfer amount, and currency code. */

public struct PeerTransferResponse: Codable {

    /** Amount of the transfer. */
    public var amount: Decimal
    public var createdTime: Date
    /** Three-digit ISO 4217 currency code. */
    public var currencyCode: String
    /** Additional descriptive text about the peer transfer. */
    public var memo: String?
    /** Specifies the business account holder that receives funds. */
    public var recipientBusinessToken: String?
    /** Specifies the user account holder that receives funds. */
    public var recipientUserToken: String?
    /** Specifies the business account holder that sends funds. */
    public var senderBusinessToken: String?
    /** Specifies the user account holder that sends funds. */
    public var senderUserToken: String?
    /** Metadata about the peer transfer. */
    public var tags: String?
    /** Unique identifier of the peer transfer request. */
    public var token: String

    public init(amount: Decimal, createdTime: Date, currencyCode: String, memo: String? = nil, recipientBusinessToken: String? = nil, recipientUserToken: String? = nil, senderBusinessToken: String? = nil, senderUserToken: String? = nil, tags: String? = nil, token: String) {
        self.amount = amount
        self.createdTime = createdTime
        self.currencyCode = currencyCode
        self.memo = memo
        self.recipientBusinessToken = recipientBusinessToken
        self.recipientUserToken = recipientUserToken
        self.senderBusinessToken = senderBusinessToken
        self.senderUserToken = senderUserToken
        self.tags = tags
        self.token = token
    }

    public enum CodingKeys: String, CodingKey { 
        case amount
        case createdTime = "created_time"
        case currencyCode = "currency_code"
        case memo
        case recipientBusinessToken = "recipient_business_token"
        case recipientUserToken = "recipient_user_token"
        case senderBusinessToken = "sender_business_token"
        case senderUserToken = "sender_user_token"
        case tags
        case token
    }

}
