//
// PeriodicFeeSchedule.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** periodic fee schedules on account */

public struct PeriodicFeeSchedule: Codable {

    public enum ModelType: String, Codable { 
        case annualFee = "ANNUAL_FEE"
        case monthlyFee = "MONTHLY_FEE"
    }
    /** fee amount */
    public var amount: Decimal?
    /** date the fee becomes effective */
    public var effectiveDate: Date?
    /** date of the next time fee will be charged */
    public var nextFeeImpactDate: Date?
    /** type of fee to be charged */
    public var type: ModelType?

    public init(amount: Decimal? = nil, effectiveDate: Date? = nil, nextFeeImpactDate: Date? = nil, type: ModelType? = nil) {
        self.amount = amount
        self.effectiveDate = effectiveDate
        self.nextFeeImpactDate = nextFeeImpactDate
        self.type = type
    }

    public enum CodingKeys: String, CodingKey { 
        case amount
        case effectiveDate = "effective_date"
        case nextFeeImpactDate = "next_fee_impact_date"
        case type
    }

}
