//
// PolicyDocumentAssetAndTemplateReq.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Request details for a specific asset and the template on which it was based. */

public struct PolicyDocumentAssetAndTemplateReq: Codable {

    /** Unique identifier of the asset, which is the version of a document that is based on the template and contains finalized values. The values are finalized when the bundle containing the document is created. */
    public var assetToken: String
    /** Unique identifier of the template, which is the version of a document that serves as an initial disclosure but does not contain finalized values. The values are finalized in the asset version of the document. */
    public var templateToken: String

    public init(assetToken: String, templateToken: String) {
        self.assetToken = assetToken
        self.templateToken = templateToken
    }

    public enum CodingKeys: String, CodingKey { 
        case assetToken = "asset_token"
        case templateToken = "template_token"
    }

}
