//
// PolicyProductResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Contains information on the credit product policy. */

public struct PolicyProductResponse: Codable {

    /** One or more card products associated with the credit product policy. */
    public var cardProducts: [PolicyProductCardProductResponse]?
    public var classification: ProductClassification?
    /** Date and time when the credit product policy was created on Marqeta&#x27;s credit platform, in UTC. */
    public var createdTime: Date?
    public var creditLine: ProductCreditLine?
    public var currencyCode: CurrencyCode?
    /** Description of the credit product policy. */
    public var _description: String?
    public var interestCalculation: InterestCalculation?
    /** Name of the credit product policy. */
    public var name: String?
    public var payments: PolicyProductPaymentConfiguration?
    public var productSubType: ProductSubType?
    public var productType: ProductType?
    /** Unique identifier of the credit product policy. */
    public var token: String?
    /** Date and time when the credit product policy was last updated on Marqeta&#x27;s credit platform, in UTC. */
    public var updatedTime: Date?
    /** One or more usage types for the credit product policy. */
    public var usage: [BalanceType]?

    public init(cardProducts: [PolicyProductCardProductResponse]? = nil, classification: ProductClassification? = nil, createdTime: Date? = nil, creditLine: ProductCreditLine? = nil, currencyCode: CurrencyCode? = nil, _description: String? = nil, interestCalculation: InterestCalculation? = nil, name: String? = nil, payments: PolicyProductPaymentConfiguration? = nil, productSubType: ProductSubType? = nil, productType: ProductType? = nil, token: String? = nil, updatedTime: Date? = nil, usage: [BalanceType]? = nil) {
        self.cardProducts = cardProducts
        self.classification = classification
        self.createdTime = createdTime
        self.creditLine = creditLine
        self.currencyCode = currencyCode
        self._description = _description
        self.interestCalculation = interestCalculation
        self.name = name
        self.payments = payments
        self.productSubType = productSubType
        self.productType = productType
        self.token = token
        self.updatedTime = updatedTime
        self.usage = usage
    }

    public enum CodingKeys: String, CodingKey { 
        case cardProducts = "card_products"
        case classification
        case createdTime = "created_time"
        case creditLine = "credit_line"
        case currencyCode = "currency_code"
        case _description = "description"
        case interestCalculation = "interest_calculation"
        case name
        case payments
        case productSubType = "product_sub_type"
        case productType = "product_type"
        case token
        case updatedTime = "updated_time"
        case usage
    }

}
