//
// PolicyRewardRule.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Contains information on a reward rule. */

public struct PolicyRewardRule: Codable {

    public var filters: PolicyRewardRuleFilters
    public var outcome: PolicyRewardRuleOutcome
    public var type: PolicyRewardRuleType

    public init(filters: PolicyRewardRuleFilters, outcome: PolicyRewardRuleOutcome, type: PolicyRewardRuleType) {
        self.filters = filters
        self.outcome = outcome
        self.type = type
    }


}
