//
// PolicyDocumentTemplateReq.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Request details for a template. */

public struct PolicyDocumentTemplateReq: Codable {

    /** Unique identifier of a template, which is a document that serves as an initial disclosure but does not contain finalized values. */
    public var templateToken: String

    public init(templateToken: String) {
        self.templateToken = templateToken
    }

    public enum CodingKeys: String, CodingKey { 
        case templateToken = "template_token"
    }

}
