//
// PolicyRewardRuleOutcome.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Contains information on the outcome of a reward rule. */

public struct PolicyRewardRuleOutcome: Codable {

    /** Max amount of the reward. */
    public var maxAmount: Decimal?
    /** The reward percentage applied when the balance for a billing cycle is within the range specified in the &#x60;filters.amount.greater_than&#x60; and &#x60;filters.amount.less_than&#x60; fields. For example, if the percentage is &#x60;1&#x60;, the account holder earns 1% of the account balance if they spend between the &#x60;greater_than&#x60; and &#x60;less_than&#x60; amounts during a billing cycle. */
    public var percentage: Decimal

    public init(maxAmount: Decimal? = nil, percentage: Decimal) {
        self.maxAmount = maxAmount
        self.percentage = percentage
    }

    public enum CodingKeys: String, CodingKey { 
        case maxAmount = "max_amount"
        case percentage
    }

}
