//
// ProductMinPaymentPercentage.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Contains information used to calculate the minimum payment percentage. */

public struct ProductMinPaymentPercentage: Codable {

    /** One or more fee types to include when calculating the minimum payment. */
    public var includeFeesCharged: [ProductFeeType]
    /** Minimum payment, expressed as a percentage of the total statement balance, due on the payment due day. */
    public var percentageOfBalance: Decimal

    public init(includeFeesCharged: [ProductFeeType], percentageOfBalance: Decimal) {
        self.includeFeesCharged = includeFeesCharged
        self.percentageOfBalance = percentageOfBalance
    }

    public enum CodingKeys: String, CodingKey { 
        case includeFeesCharged = "include_fees_charged"
        case percentageOfBalance = "percentage_of_balance"
    }

}
