//
// ProductConfig.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Contains information on configurations for billing cycle day, payment due day, and fees. */

public struct ProductConfig: Codable {

    /** Day of month the billing cycle starts. */
    public var billingCycleDay: Int
    /** One or more fee types. */
    public var fees: [ProductFeeType]?
    /** Day of month the payment for the previous billing cycle is due. */
    public var paymentDueDay: Int
    /** Contains one or more periodic fees. */
    public var periodicFees: [ProductConfigPeriodicFees]?

    public init(billingCycleDay: Int, fees: [ProductFeeType]? = nil, paymentDueDay: Int, periodicFees: [ProductConfigPeriodicFees]? = nil) {
        self.billingCycleDay = billingCycleDay
        self.fees = fees
        self.paymentDueDay = paymentDueDay
        self.periodicFees = periodicFees
    }

    public enum CodingKeys: String, CodingKey { 
        case billingCycleDay = "billing_cycle_day"
        case fees
        case paymentDueDay = "payment_due_day"
        case periodicFees = "periodic_fees"
    }

}
