//
// ProgramTransferTypeRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ProgramTransferTypeRequest: Codable {

    /** Memo or note describing the program transfer type. */
    public var memo: String
    /** Unique identifier of the program funding source to which program transfers will be credited.  Send a &#x60;GET&#x60; request to &#x60;/fundingsources/program&#x60; to retrieve program funding source tokens. */
    public var programFundingSourceToken: String
    /** Comma-delimited list of tags describing the program transfer type. */
    public var tags: String?
    /** Unique identifier of the program transfer type.  If you do not include a token, the system will generate one automatically. This token is necessary for use in other API calls, so we recommend that rather than let the system generate one, you use a simple string that is easy to remember. This value cannot be updated. */
    public var token: String?

    public init(memo: String, programFundingSourceToken: String, tags: String? = nil, token: String? = nil) {
        self.memo = memo
        self.programFundingSourceToken = programFundingSourceToken
        self.tags = tags
        self.token = token
    }

    public enum CodingKeys: String, CodingKey { 
        case memo
        case programFundingSourceToken = "program_funding_source_token"
        case tags
        case token
    }

}
