//
// PushToCardDisbursementResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PushToCardDisbursementResponse: Codable {

    public var amount: Decimal?
    /** yyyy-MM-ddTHH:mm:ssZ */
    public var createdTime: Date
    public var currencyCode: String?
    /** yyyy-MM-ddTHH:mm:ssZ */
    public var lastModifiedTime: Date
    public var memo: String?
    public var paymentInstrumentToken: String?
    public var status: String?
    public var tags: String?
    public var token: String?

    public init(amount: Decimal? = nil, createdTime: Date, currencyCode: String? = nil, lastModifiedTime: Date, memo: String? = nil, paymentInstrumentToken: String? = nil, status: String? = nil, tags: String? = nil, token: String? = nil) {
        self.amount = amount
        self.createdTime = createdTime
        self.currencyCode = currencyCode
        self.lastModifiedTime = lastModifiedTime
        self.memo = memo
        self.paymentInstrumentToken = paymentInstrumentToken
        self.status = status
        self.tags = tags
        self.token = token
    }

    public enum CodingKeys: String, CodingKey { 
        case amount
        case createdTime = "created_time"
        case currencyCode = "currency_code"
        case lastModifiedTime = "last_modified_time"
        case memo
        case paymentInstrumentToken = "payment_instrument_token"
        case status
        case tags
        case token
    }

}
