//
// PutRewardProgramsRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PutRewardProgramsRequest: Codable {

    /** A value of &#x60;true&#x60; indicates that the reward program is active and rewards can be accrued for the associated account. */
    public var isActive: Bool
    /** A note explaining why the reward program is being activated or deactivated. */
    public var note: String

    public init(isActive: Bool, note: String) {
        self.isActive = isActive
        self.note = note
    }

    public enum CodingKeys: String, CodingKey { 
        case isActive = "is_active"
        case note
    }

}
