//
// RealTimeFeeAssessment.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Controls the assessment of real-time fees. */

public struct RealTimeFeeAssessment: Codable {

    /** Enables fee assessments where the origin of the transaction acquirer is inside the US. */
    public var domesticEnabled: Bool?
    /** Enables fee assessments where the origin of the transaction acquirer is outside the US. */
    public var internationalEnabled: Bool?
    /** Indicates the type of transactions on which the fee is assessed. */
    public var transactionType: String?

    public init(domesticEnabled: Bool? = nil, internationalEnabled: Bool? = nil, transactionType: String? = nil) {
        self.domesticEnabled = domesticEnabled
        self.internationalEnabled = internationalEnabled
        self.transactionType = transactionType
    }

    public enum CodingKeys: String, CodingKey { 
        case domesticEnabled = "domestic_enabled"
        case internationalEnabled = "international_enabled"
        case transactionType = "transaction_type"
    }

}
