//
// RedemptionStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Status of the redemption.  If &lt;&lt;/core-api/reward-redemptions#postRedemptionTransition, transitioning the redemption&#x27;s status&gt;&gt;:  * &#x60;new_state&#x60; is the state to which you want to transition the redemption; must be &#x60;COMPLETED&#x60; or &#x60;RETURNED&#x60;.  * &#x60;initial_status&#x60; is the initial status of the redemption prior to transition. */
public enum RedemptionStatus: String, Codable {
    case initiated = "INITIATED"
    case completed = "COMPLETED"
    case returned = "RETURNED"
    case processing = "PROCESSING"
    case submitted = "SUBMITTED"
}