//
// RefundDetailsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Contains details for a refund. */

public struct RefundDetailsResponse: Codable {

    /** Description of the refund. */
    public var _description: String
    public var method: RefundMethod
    public var status: RefundStatus

    public init(_description: String, method: RefundMethod, status: RefundStatus) {
        self._description = _description
        self.method = method
        self.status = status
    }

    public enum CodingKeys: String, CodingKey { 
        case _description = "description"
        case method
        case status
    }

}
