//
// ResetUserPasswordEmailModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ResetUserPasswordEmailModel: Codable {

    /** Cardholder email address. */
    public var email: String

    public init(email: String) {
        self.email = email
    }


}
