//
// RewardType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Type of reward. */
public enum RewardType: String, Codable {
    case autoCashBack = "AUTO_CASH_BACK"
    case cashBack = "CASH_BACK"
}