//
// Shipping.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Specifies shipping details for the order. */

public struct Shipping: Codable {

    public enum Method: String, Codable { 
        case localMail = "LOCAL_MAIL"
        case localMailPackage = "LOCAL_MAIL_PACKAGE"
        case ground = "GROUND"
        case twoDay = "TWO_DAY"
        case overnight = "OVERNIGHT"
        case international = "INTERNATIONAL"
        case internationalPriority = "INTERNATIONAL_PRIORITY"
        case localPriority = "LOCAL_PRIORITY"
        case fedexExpedited = "FEDEX_EXPEDITED"
        case fedexRegular = "FEDEX_REGULAR"
        case upsExpedited = "UPS_EXPEDITED"
        case upsRegular = "UPS_REGULAR"
        case uspsExpedited = "USPS_EXPEDITED"
        case uspsRegular = "USPS_REGULAR"
    }
    /** Adds the specified value as a care of (C/O) line to the mailing carrier.  *NOTE:* This field can be specified on cards, card products, and bulk card orders. If you specify this field at multiple levels, the order of precedence is: card, bulk card order, card product. */
    public var careOfLine: String?
    /** Specifies the shipping service. */
    public var method: Method?
    public var recipientAddress: FulfillmentAddressRequest?
    public var returnAddress: FulfillmentAddressRequest?

    public init(careOfLine: String? = nil, method: Method? = nil, recipientAddress: FulfillmentAddressRequest? = nil, returnAddress: FulfillmentAddressRequest? = nil) {
        self.careOfLine = careOfLine
        self.method = method
        self.recipientAddress = recipientAddress
        self.returnAddress = returnAddress
    }

    public enum CodingKeys: String, CodingKey { 
        case careOfLine = "care_of_line"
        case method
        case recipientAddress = "recipient_address"
        case returnAddress = "return_address"
    }

}
