//
// StatementFile.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A collection of statement files. */

public struct StatementFile: Codable {

    public enum ModelType: String, Codable { 
        case statementPdf = "STATEMENT_PDF"
    }
    /** Unique identifier of the credit account on which the statement PDF file is generated. */
    public var accountToken: String?
    /** Date and time when the statement period ended. */
    public var closingDate: Date?
    /** Date and time when the statement period began. */
    public var openingDate: Date?
    /** The signed URL to retrieve the statement PDF file. */
    public var signedUrl: String?
    /** Unique identifier of the statement summary. */
    public var statementSummaryToken: UUID?
    /** Unique identifier of the statement file. */
    public var token: String?
    /** Type of file. */
    public var type: ModelType?

    public init(accountToken: String? = nil, closingDate: Date? = nil, openingDate: Date? = nil, signedUrl: String? = nil, statementSummaryToken: UUID? = nil, token: String? = nil, type: ModelType? = nil) {
        self.accountToken = accountToken
        self.closingDate = closingDate
        self.openingDate = openingDate
        self.signedUrl = signedUrl
        self.statementSummaryToken = statementSummaryToken
        self.token = token
        self.type = type
    }

    public enum CodingKeys: String, CodingKey { 
        case accountToken = "account_token"
        case closingDate = "closing_date"
        case openingDate = "opening_date"
        case signedUrl = "signed_url"
        case statementSummaryToken = "statement_summary_token"
        case token
        case type
    }

}
