//
// UnloadRequestModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UnloadRequestModel: Codable {

    /** Amount of funds to return to the funding source. */
    public var amount: Decimal
    /** Unique identifier of the funding source to use for this GPA unload order.  Send a &#x60;GET&#x60; request to &#x60;/fundingsources/addresses/user/{token}&#x60; to retrieve addresses for a specific user. */
    public var fundingSourceAddressToken: String?
    /** Additional descriptive text about the GPA unload. */
    public var memo: String?
    /** Unique identifier of the original GPA order. */
    public var originalOrderToken: String
    /** Comma-delimited list of tags describing the GPA unload order. */
    public var tags: String?
    /** Unique identifier of the GPA unload order.  If you do not include a token, the system will generate one automatically. This token is necessary for use in other calls, so we recommend that rather than let the system generate one, you use a simple string that is easy to remember. This value cannot be updated. */
    public var token: String?

    public init(amount: Decimal, fundingSourceAddressToken: String? = nil, memo: String? = nil, originalOrderToken: String, tags: String? = nil, token: String? = nil) {
        self.amount = amount
        self.fundingSourceAddressToken = fundingSourceAddressToken
        self.memo = memo
        self.originalOrderToken = originalOrderToken
        self.tags = tags
        self.token = token
    }

    public enum CodingKeys: String, CodingKey { 
        case amount
        case fundingSourceAddressToken = "funding_source_address_token"
        case memo
        case originalOrderToken = "original_order_token"
        case tags
        case token
    }

}
