//
// UserValidationResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Contains information about the user. */

public struct UserValidationResponse: Codable {

    /** Indicates whether the &#x60;birth_date&#x60; field in the request was validated. */
    public var birthDate: Bool
    /** Indicates whether the &#x60;phone&#x60; field in the request was validated. */
    public var phone: Bool
    /** Indicates whether the &#x60;random_name_line1_postfix&#x60; field in the request was validated. */
    public var randomNameLine1Postfix: Bool
    /** Indicates whether the &#x60;ssn&#x60; field in the request was validated. */
    public var ssn: Bool

    public init(birthDate: Bool, phone: Bool, randomNameLine1Postfix: Bool, ssn: Bool) {
        self.birthDate = birthDate
        self.phone = phone
        self.randomNameLine1Postfix = randomNameLine1Postfix
        self.ssn = ssn
    }

    public enum CodingKeys: String, CodingKey { 
        case birthDate = "birth_date"
        case phone
        case randomNameLine1Postfix = "random_name_line1_postfix"
        case ssn
    }

}
