//
// UserAssociation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Associates each card with a user. */

public struct UserAssociation: Codable {

    /** Set to &#x60;true&#x60; to associate all cards with the same user. Set to &#x60;false&#x60; to associate each card with a different user. When set to &#x60;false&#x60;, users are generated automatically and associated with the cards. */
    public var singleInventoryUser: Bool?
    /** If &#x60;single_inventory_user&#x3D;true&#x60;, use this field to specify the token of an existing user. All cards in the order will be associated with this user. */
    public var singleInventoryUserToken: String?

    public init(singleInventoryUser: Bool? = nil, singleInventoryUserToken: String? = nil) {
        self.singleInventoryUser = singleInventoryUser
        self.singleInventoryUserToken = singleInventoryUserToken
    }

    public enum CodingKeys: String, CodingKey { 
        case singleInventoryUser = "single_inventory_user"
        case singleInventoryUserToken = "single_inventory_user_token"
    }

}
