//
// Webhook.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Webhook: Codable {

    /** Valid URL */
    public var endpoint: String
    /** Authentication password */
    public var password: String
    /** Authentication secret */
    public var secret: String?
    /** Authentication username */
    public var username: String

    public init(endpoint: String, password: String, secret: String? = nil, username: String) {
        self.endpoint = endpoint
        self.password = password
        self.secret = secret
        self.username = username
    }


}
